dailycheck/urls.py
from django.urls import path
from . import views


app_name = "dailycheck"
urlpatterns = [
    path("", views.home, name="home"),
    path("school/", views.school_list, name="school-list"),
    path(
        "attendance-choose/<int:school_id>/",
        views.attendance_choose,
        name="attendance-choose",
    ),
    path("attendance-get/", views.attendance_get, name="attendance-get"),
    path("attendance-save/", views.attendance_save, name="attendance-save"),
    path(
        "attendance-save-done/", views.attendance_save_done, name="attendance-save-done"
    ),
    path(
        "signature/<int:signature_id>/", views.signature_detail, name="signature-detail"
    ),
]

ohaschoolbusv6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("dailycheck.urls")),
    path("admin/", admin.site.urls),
]

dailycheck/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=255)
    post_code = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class School(models.Model):
    name = models.CharField(max_length=255)
    code = models.IntegerField()
    city = models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)
    district = models.ForeignKey(
        District, on_delete=models.CASCADE, blank=True, null=True
    )
    address_detail = models.CharField(max_length=512, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dailycheck:school-detail", kwargs={"pk": self.pk})


class Village(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dailycheck:village-detail", kwargs={"pk": self.pk})


class Driver(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Bus(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.SET_NULL, blank=True, null=True)
    bus_number = models.CharField(max_length=255)
    capacity = models.IntegerField()
    plate = models.CharField(max_length=11)
    village = models.ManyToManyField(Village)

    class Meta:
        ordering = ["bus_number"]

    def __str__(self):
        return self.bus_number


class Grade(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    level = models.CharField(max_length=255)
    branch = models.CharField(max_length=255)

    class Meta:
        ordering = ["level"]

    def __str__(self):
        return f"{self.level}/{self.branch}"


class Student(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    # evening_bus = models.ForeignKey(Bus, on_delete=models.RESTRICT)
    village = models.ForeignKey(Village, on_delete=models.CASCADE)

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.first_name}  {self.last_name}"


class Person(models.Model):
    ROLE_CHOICES = (
        ("1", "Admin"),
        ("2", "Manager"),
        ("3", "Teacher"),
        ("4", "Standard"),
    )
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    role = models.CharField(max_length=1, choices=ROLE_CHOICES, default="3")

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return self.username


class Signature(models.Model):
    DIRECTION_CHOICES = (
        ("coming", "Coming"),
        ("leaving", "Leaving"),
    )
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    check_date = models.DateField()
    direction = models.CharField(max_length=7, choices=DIRECTION_CHOICES)
    teacher = models.ForeignKey(Person, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    signed_at = models.DateTimeField(auto_now=True)
    is_signed = models.BooleanField(default=False)

    @property
    def number_of_absent_student(self):
        return Attendance.objects.filter(signature=self.id).count()
        # return self.attendance_set.count()

    @property
    def number_of_total_student(self):
        return Student.objects.filter(bus=self.bus).count()

    class Meta:
        ordering = ["-check_date"]
        constraints = [
            models.UniqueConstraint(
                fields=["school", "bus", "check_date", "direction"],
                name="unique_signature_with_school_bus_date_and_direction",
            )
        ]

    def __str__(self):
        return (
            f"{self.school.id} | {self.bus.id} | {self.check_date} | {self.direction} | "
            f"{self.number_of_absent_student} | {self.number_of_total_student} | {self.teacher.id} | "
            f"{self.created_at} | {self.signed_at} | {self.is_signed}"
        )

    def get_absolute_url(self):
        return reverse("signature-detail", kwargs={"pk": self.pk})


class Attendance(models.Model):
    signature = models.ForeignKey(Signature, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-signature"]
        constraints = [
            models.UniqueConstraint(
                fields=["student", "signature"],
                name="unique_attendance_with_student_and_signature",
            )
        ]

    def __str__(self):
        return f"{self.signature.id} | {self.student}"

dailycheck/views.py
import datetime

from django.core import serializers
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse

from .models import School, Person, Bus, Student, Attendance, Signature

# General data for easy implementation
teacher = Person.objects.get(id=1)


def home(request):
    return redirect("dailycheck:school-list")


def school_list(request):
    context = {"school_list": School.objects.all()}
    return render(request, "dailycheck/school_list.html", context)


def attendance_choose(request, school_id):
    # Show menu to Choose bus, date, direction
    # School and user comes automatic with session
    request.session["school_id"] = school_id
    school = get_object_or_404(School.objects.all(), id=school_id)
    bus_list = Bus.objects.filter(school=school)
    context = {"bus_list": bus_list, "today": datetime.date.today()}
    return render(request, "dailycheck/attendance_choose.html", context)


def attendance_get(request):
    school = get_object_or_404(School.objects.all(), id=request.session["school_id"])
    bus = get_object_or_404(Bus.objects.all(), id=request.POST.get("bus"))
    check_date = request.POST.get("check_date")
    direction = request.POST.get("direction")
    student_list = Student.objects.filter(bus=bus)

    # Get or create new signature
    # fields = ["school", "bus", "check_date", "direction"],
    signature, created = Signature.objects.get_or_create(
        school=school,
        bus=bus,
        direction=direction,
        check_date=check_date,
        defaults={"teacher": teacher},
    )

    request.session["signature_id"] = signature.id

    # If signature is already exist get unattended student list
    student_already_absent_list = []
    if not created:
        student_already_absent_list = Student.objects.filter(
            attendance__signature=signature
        )

    context = {
        "student_list": student_list,
        "student_already_absent_list": student_already_absent_list,
        "signature": signature,
    }
    return render(request, "dailycheck/attendance_get.html", context)


def attendance_save(request):
    """Save attendance logic"""
    if request.method == "POST":
        student_absent_list = request.POST.getlist("student_absent_list")

        # Delete all attendance for signature
        signature = Signature.objects.get(id=request.session["signature_id"])
        Attendance.objects.filter(signature=signature).delete()

        # Add absent students to Attendance
        for student in student_absent_list:
            Attendance.objects.create(signature=signature, student_id=student)

        # Touch Signature Model for update to signed_at field
        signature.is_signed = True
        signature.save()

        # return redirect("dailycheck:signature-detail", signature.id)
        return redirect("dailycheck:attendance-save-done")


def attendance_save_done(request):
    signature = get_object_or_404(
        Signature.objects.all(), id=request.session["signature_id"]
    )
    context = {"signature": signature}
    return render(request, "dailycheck/attendance_save_done.html", context)


def signature_detail(request, signature_id):
    signature = get_object_or_404(Signature.objects.all(), id=signature_id)
    context = {"signature": signature}
    return render(request, "dailycheck/signature_detail.html", context)

dailycheck/templates/dailycheck/attendance_choose.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Choose</title>
</head>
<body>

<h1>Attendance Choose</h1>
<form method="post" action="{% url 'dailycheck:attendance-get' %}">{% csrf_token %}
    Bus:
    <select name="bus" required id="bus">
        <option value selected>-----</option>
        {% for bus in bus_list %}
            <option value="{{ bus.id }}">{{ bus.bus_number }}</option>
        {% endfor %}
    </select>

    <label for="check_date">Date:</label>
    <input type="date" id="check_date" name="check_date" value="{{ today|date:'Y-m-d' }}"><br>
    Direction:
    <input type="radio" id="coming" name="direction" value="coming">
    <label for="coming">Coming</label>
    <input type="radio" id="leaving" name="direction" value="leaving">
    <label for="leaving">Leaving</label><br>

    <input type="submit" value="Save">
</form>

<a href="{% url 'dailycheck:school-list' %}">Home page</a>
</body>
</html>

dailycheck/templates/dailycheck/attendance_get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance get</title>
</head>
<body>

<h1>Bus: {{ signature.bus }}, {{ signature.check_date }} - {{ signature.direction }}</h1>
<p>Signature: {{ signature }}</p>

<form method="post" action="{% url 'dailycheck:attendance-save' %}">{% csrf_token %}
    Student Name | Absent <br>
    {% for student in student_list %}
        <label for="student_absent_list{{ forloop.counter }}"> {{ student.first_name }}</label>
        <input type="checkbox" id="student_absent_list{{ forloop.counter }}" name="student_absent_list"
               value="{{ student.id }}" {% if student in student_already_absent_list %} checked{% endif %}>
        <br>
    {% empty %}
        <li>Sorry, no students in this list.</li>
    {% endfor %}
    <input type="submit" value="Save">
</form>

</body>
</html>

dailycheck/templates/dailycheck/attendance_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance List</title>
</head>
<body>
<h1>Attendance List</h1>
<p>Absent Student List</p>
{% if object_list %}
    <ul>
    <li>id - check_date - check_direction - student - person</li>
    {% for attendance in object_list %}
        <li>{{ attendance.id }} - {{ attendance.check_date }} - {{ attendance.get_check_direction_display }}
            - {{ attendance.student }} - {{ attendance.person }}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No unattended are available.</p>
{% endif %}
</body>
</html>

dailycheck/templates/dailycheck/attendance_save_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Successful Saved</title>
</head>
<body>
<h1>{{ signature }}</h1>

<script>
    alert("Bus: {{ signature.bus }}, {{ signature.check_date }} - {{ signature.direction }} successful recorded.");
    location.replace("{% url 'dailycheck:signature-detail' signature.id %}");
</script>

</body>
</html>

dailycheck/templates/dailycheck/school_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>School List</title>
</head>
<body>

<h1>School List</h1>
<ul>
{% for school in school_list %}
    <li><a href="{% url 'dailycheck:attendance-choose' school.id %}">{{ school }}</a></li>
{% empty %}
    <li>Sorry, no schools in this list.</li>
{% endfor %}
</ul>
</body>
</html>

dailycheck/templates/dailycheck/signature_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signiture Detail</title>
</head>
<body>

<h1>Bus: {{ signature.bus }}, {{ signature.check_date }} - {{ signature.direction }}</h1>
Total students number: {{ signature.number_of_total_student }}<br>
Absents students number: {{ signature.number_of_absent_student }}

<h2>Attendance:</h2>
<ul>
    {% for attendance in signature.attendance_set.all %}
        <li>{{ attendance.student }}</li>
    {% empty %}
        <li>All students are on the bus.</li>
    {% endfor %}
</ul>

<a href="{% url 'dailycheck:attendance-choose' request.session.school_id %}">Get new attendance</a>

</body>
</html>